services:
  mysql:
    image: mysql:8.0
    container_name: loja_brinquedos_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: LojaDeBrinquedos
      MYSQL_USER: loja_user
      MYSQL_PASSWORD: loja123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - loja_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  loja_network:
    driver: bridge
